export interface DataSource {
  id: string;
  name: string;
  url: string;
  type: 'API' | 'Website';
  description: string;
  requiresAuth: boolean;
  authMethod: 'None' | 'API Key' | 'Bearer Token';
  credentials?: string;
  isSystemSource: boolean;
}

export const systemDataSources: DataSource[] = [
  {
    id: 'dgo',
    name: 'DGO - Direção-Geral do Orçamento',
    url: 'https://www.dgo.gov.pt',
    type: 'Website',
    description: 'Entidade responsável pela elaboração e controlo do Orçamento do Estado em Portugal.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'transparencia',
    name: 'Portal da Transparência',
    url: 'https://www.transparencia.gov.pt',
    type: 'Website',
    description: 'Portal oficial para consulta de execução orçamental e fundos europeus.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'ine',
    name: 'INE - Instituto Nacional de Estatística',
    url: 'https://www.ine.pt',
    type: 'Website',
    description: 'Principal produtor de estatísticas oficiais em Portugal.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'pordata',
    name: 'Pordata',
    url: 'https://www.pordata.pt',
    type: 'Website',
    description: 'Base de dados sobre Portugal com estatísticas da sociedade.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'banco-portugal',
    name: 'Banco de Portugal',
    url: 'https://www.bportugal.pt/estatisticas',
    type: 'Website',
    description: 'Fonte para estatísticas monetárias e financeiras.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'eurostat',
    name: 'Eurostat',
    url: 'https://ec.europa.eu/eurostat/data/database',
    type: 'Website',
    description: 'Serviço de estatística da União Europeia.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'dre',
    name: 'Diário da República Eletrónico',
    url: 'https://diariodarepublica.pt',
    type: 'Website',
    description: 'Fonte oficial para toda a legislação e atos do governo.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'aima',
    name: 'AIMA - Agência para a Integração, Migrações e Asilo',
    url: 'https://aima.gov.pt',
    type: 'Website',
    description: 'Entidade responsável pelas políticas públicas de migração, asilo e integração de imigrantes em Portugal.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'lusa',
    name: 'Agência Lusa',
    url: 'https://www.lusa.pt',
    type: 'Website',
    description: 'Principal agência de notícias de Portugal.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'rtp',
    name: 'RTP Notícias',
    url: 'https://www.rtp.pt/noticias',
    type: 'Website',
    description: 'Serviço público de rádio e televisão.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'sic',
    name: 'SIC Notícias',
    url: 'https://sicnoticias.pt',
    type: 'Website',
    description: 'Canal de notícias de referência.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'cnn',
    name: 'CNN Portugal',
    url: 'https://cnnportugal.iol.pt',
    type: 'Website',
    description: 'Canal de notícias internacional adaptado a Portugal.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'publico',
    name: 'Público',
    url: 'https://www.publico.pt',
    type: 'Website',
    description: 'Jornal diário de referência.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'expresso',
    name: 'Expresso',
    url: 'https://expresso.pt',
    type: 'Website',
    description: 'Semanário de referência em Portugal.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'observador',
    name: 'Observador',
    url: 'https://observador.pt',
    type: 'Website',
    description: 'Jornal digital focado em opinião e análise.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  },
  {
    id: 'tsf',
    name: 'TSF Rádio Notícias',
    url: 'https://www.tsf.pt',
    type: 'Website',
    description: 'Rádio nacional de notícias.',
    requiresAuth: false,
    authMethod: 'None',
    isSystemSource: true,
  }
];
