export interface DataSource {
  id: string;
  name: string;
  url: string;
  type: 'API' | 'Website';
  description: string;
  requiresAuth: boolean;
  authMethod: 'None' | 'API Key' | 'Bearer Token';
  dataCategories: string[];
  isSystemSource?: boolean;
}

// This is a curated list of foundational data sources for the application.
// These sources are considered essential and are managed by the system.
export const getSystemDataSources = (): DataSource[] => {
  return [
    {
      id: 'pordata',
      name: 'Pordata',
      url: 'https://www.pordata.pt/',
      type: 'Website',
      description: 'Base de Dados de Portugal Contemporâneo, mantida pela Fundação Francisco Manuel dos Santos.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Estatísticas Oficiais', 'Dados Demográficos', 'Dados Sociais'],
      isSystemSource: true,
    },
    {
      id: 'ine',
      name: 'Instituto Nacional de Estatística (INE)',
      url: 'https://www.ine.pt/',
      type: 'Website',
      description: 'Principal produtor de estatísticas oficiais em Portugal.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Estatísticas Oficiais', 'Dados Macroeconómicos', 'Censos'],
      isSystemSource: true,
    },
    {
      id: 'dgo',
      name: 'Direção-Geral do Orçamento (DGO)',
      url: 'https://www.dgo.gov.pt/',
      type: 'Website',
      description: 'Responsável pela elaboração, execução e controlo do Orçamento do Estado.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Finanças Públicas', 'Orçamento de Estado'],
      isSystemSource: true,
    },
    {
      id: 'bportugal',
      name: 'Banco de Portugal',
      url: 'https://www.bportugal.pt/',
      type: 'Website',
      description: 'Banco central da República Portuguesa.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Estatísticas Monetárias', 'Dados Macroeconómicos', 'Sistema Financeiro'],
      isSystemSource: true,
    },
    {
      id: 'eurostat',
      name: 'Eurostat',
      url: 'https://ec.europa.eu/eurostat',
      type: 'Website',
      description: 'Gabinete de estatísticas da União Europeia.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Estatísticas Europeias', 'Dados Macroeconómicos'],
      isSystemSource: true,
    },
    {
      id: 'worldbank',
      name: 'World Bank Open Data',
      url: 'https://data.worldbank.org/',
      type: 'Website',
      description: 'Dados de desenvolvimento global gratuitos e de acesso aberto.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Dados Internacionais', 'Desenvolvimento Económico'],
      isSystemSource: true,
    },
    {
      id: 'dbnomics',
      name: 'DBnomics',
      url: 'https://db.nomics.world/',
      type: 'API',
      description: 'Agregador de dados económicos e financeiros de várias fontes públicas.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Dados Macroeconómicos', 'Séries Temporais', 'Dados Internacionais'],
      isSystemSource: true,
    },
    {
      id: 'rtp',
      name: 'RTP Notícias',
      url: 'https://www.rtp.pt/noticias/',
      type: 'Website',
      description: 'Serviço público de notícias de rádio e televisão.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias'],
      isSystemSource: true,
    },
    {
      id: 'lusa',
      name: 'Agência Lusa',
      url: 'https://www.lusa.pt/',
      type: 'Website',
      description: 'Agência de notícias estatal de Portugal.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias'],
      isSystemSource: true,
    },
    {
      id: 'sic',
      name: 'SIC Notícias',
      url: 'https://sicnoticias.pt',
      type: 'Website',
      description: 'Canal de notícias de referência.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias'],
      isSystemSource: true,
    },
    {
      id: 'cnn',
      name: 'CNN Portugal',
      url: 'https://cnnportugal.iol.pt',
      type: 'Website',
      description: 'Canal de notícias internacional adaptado a Portugal.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias'],
      isSystemSource: true,
    },
    {
      id: 'publico',
      name: 'Público',
      url: 'https://www.publico.pt',
      type: 'Website',
      description: 'Jornal diário de referência.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias', 'Opinião'],
      isSystemSource: true,
    },
    {
      id: 'expresso',
      name: 'Expresso',
      url: 'https://expresso.pt',
      type: 'Website',
      description: 'Semanário de referência em Portugal.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias', 'Opinião', 'Análise'],
      isSystemSource: true,
    },
    {
      id: 'observador',
      name: 'Observador',
      url: 'https://observador.pt',
      type: 'Website',
      description: 'Jornal digital focado em opinião e análise.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias', 'Opinião', 'Análise'],
      isSystemSource: true,
    },
    {
      id: 'tsf',
      name: 'TSF Rádio Notícias',
      url: 'https://www.tsf.pt',
      type: 'Website',
      description: 'Rádio nacional de notícias.',
      requiresAuth: false,
      authMethod: 'None',
      dataCategories: ['Notícias'],
      isSystemSource: true,
    },
    {
      id: 'alpha-vantage',
      name: 'Alpha Vantage',
      url: 'https://www.alphavantage.co',
      type: 'API',
      description: 'API for real-time and historical data on stocks, forex, and cryptocurrencies.',
      requiresAuth: true,
      authMethod: 'API Key',
      dataCategories: ['Cotações de Ações', 'Dados Financeiros', 'Séries Temporais'],
      isSystemSource: true,
    },
    {
      id: 'financial-modeling-prep',
      name: 'Financial Modeling Prep',
      url: 'https://financialmodelingprep.com/',
      type: 'API',
      description: 'API for real-time and historical financial data, including stocks, forex, and cryptocurrencies.',
      requiresAuth: true,
      authMethod: 'API Key',
      dataCategories: ['Cotações de Ações', 'Dados Financeiros', 'Perfis de Empresas', 'Dados Históricos'],
      isSystemSource: true,
    }
  ];
};
