name = "demokratia"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public", "unsafe_eval"]

pages_build_output_dir = ".open-next"


[[d1_databases]]
binding = "DB"
database_name = "demokratia-db"
database_id = "b22a35d4-d754-4862-ad18-08776dcc97ff"

[[kv_namespaces]]
binding = "KV"
id = "e5245242b82b4b4eb8ee014c237c3cdd"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_aHVtYW5lLW1vbmtleS0yNS5jbGVyay5hY2NvdW50cy5kZXYk"
# e NÃO colocadas aqui (este ficheiro está no git)
